### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by gatordevin** [ieee8023/countception#1]
Hi I was wondering what the version of all the libraries being used are. So what version of theano and lasagne etc.

**Comment by ieee8023** [comment]
You should use this code instead: https://github.com/roggirg/count-ception_mbm

But here are the versions anyway:
theano 0.10.0dev1.dev-69bcff08b99064cdf7a0775cb99d8ac6f8f14cdb
lasagne 0.2.dev1
